[pytest]
DJANGO_SETTINGS_MODULE = zhongbei_info.settings_test
python_files = tests.py test_*.py *_tests.py
filterwarnings =
    ignore:The default value of `allowed_objects` will change.*:langchain_core._api.deprecation.LangChainPendingDeprecationWarning
