# Generated by Django 5.2.1 on 2026-05-10 14:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CrawlJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_url', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('queued', '排队中'), ('running', '运行中'), ('succeeded', '成功'), ('failed', '失败')], default='queued', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': '抓取任务',
                'verbose_name_plural': '抓取任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('url', models.URLField(max_length=500, unique=True)),
                ('source_type', models.CharField(choices=[('official_site', '中北官网'), ('college_site', '学院官网'), ('department_site', '部门网站'), ('social_link', '社媒链接'), ('wechat_link', '公众号链接'), ('manual_url', '手动链接')], max_length=40)),
                ('priority', models.IntegerField(choices=[(10, '重点源'), (50, '普通源'), (100, '低频源')], default=50)),
                ('crawl_interval_minutes', models.PositiveIntegerField(default=360)),
                ('enabled', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('last_crawled_at', models.DateTimeField(blank=True, null=True)),
                ('next_crawl_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('failure_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': '信息源',
                'verbose_name_plural': '信息源',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('canonical_url', models.URLField(max_length=500, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('content_text', models.TextField()),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ai_provider', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('queued', '排队中'), ('fetched', '已抓取'), ('cleaned', '已清洗'), ('ocr_done', 'OCR完成'), ('classified', '已分类'), ('published', '已发布'), ('failed', '失败'), ('blocked', '已屏蔽')], default='queued', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('source_published_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aggregator.category')),
            ],
            options={
                'verbose_name': '内容',
                'verbose_name_plural': '内容',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_url', models.URLField(max_length=500)),
                ('attachment_type', models.CharField(choices=[('image', '图片'), ('video', '视频'), ('other', '其他')], default='image', max_length=20)),
                ('ocr_text', models.TextField(blank=True)),
                ('processed', models.BooleanField(default=False)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='aggregator.contentitem')),
            ],
            options={
                'verbose_name': '附件',
                'verbose_name_plural': '附件',
            },
        ),
        migrations.CreateModel(
            name='AIJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('queued', '排队中'), ('succeeded', '成功'), ('failed', '失败')], default='queued', max_length=20)),
                ('prompt', models.TextField(blank=True)),
                ('response_json', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_jobs', to='aggregator.contentitem')),
            ],
            options={
                'verbose_name': 'AI任务',
                'verbose_name_plural': 'AI任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DuplicateGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('canonical_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canonical_for_groups', to='aggregator.contentitem')),
            ],
            options={
                'verbose_name': '重复组',
                'verbose_name_plural': '重复组',
            },
        ),
        migrations.AddField(
            model_name='contentitem',
            name='duplicate_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aggregator.duplicategroup'),
        ),
        migrations.CreateModel(
            name='RawDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=500)),
                ('final_url', models.URLField(blank=True, max_length=500)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('html', models.TextField(blank=True)),
                ('extracted_text', models.TextField(blank=True)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('crawl_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aggregator.crawljob')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_documents', to='aggregator.source')),
            ],
            options={
                'verbose_name': '原始文档',
                'verbose_name_plural': '原始文档',
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.AddField(
            model_name='contentitem',
            name='raw_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aggregator.rawdocument'),
        ),
        migrations.AddField(
            model_name='crawljob',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawl_jobs', to='aggregator.source'),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_items', to='aggregator.source'),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='tags',
            field=models.ManyToManyField(blank=True, to='aggregator.tag'),
        ),
        migrations.AddConstraint(
            model_name='rawdocument',
            constraint=models.UniqueConstraint(fields=('source', 'content_hash'), name='unique_source_raw_hash'),
        ),
    ]
