# Generated by Django 5.2.1 on 2026-05-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='importance_score',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='source',
            name='crawl_depth',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='source',
            name='max_articles_per_run',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='source',
            name='max_list_pages_per_run',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
