# Generated by Django 5.2.1 on 2026-05-11 13:43

import django.db.models.deletion
from django.db import migrations, models
from urllib.parse import urlsplit


def backfill_review_state_and_sources(apps, schema_editor):
    Source = apps.get_model("aggregator", "Source")
    ContentItem = apps.get_model("aggregator", "ContentItem")
    ContentSource = apps.get_model("aggregator", "ContentSource")

    for source in Source.objects.all():
        updates = []
        if not source.schedule_group:
            if source.source_type == "manual_url":
                source.schedule_group = "manual"
            elif source.source_type in {"social_link", "wechat_link"}:
                source.schedule_group = "social_daily"
            else:
                source.schedule_group = "web_twice_daily"
            updates.append("schedule_group")
        if not source.allowed_domains:
            hostname = urlsplit(source.url).hostname
            if hostname:
                source.allowed_domains = [hostname]
                updates.append("allowed_domains")
        if updates:
            source.save(update_fields=updates)

    ContentItem.objects.update(is_public=True, review_status="published")
    for item in ContentItem.objects.select_related("source", "raw_document"):
        ContentSource.objects.get_or_create(
            content_item_id=item.id,
            source_id=item.source_id,
            url=item.canonical_url,
            defaults={
                "raw_document_id": item.raw_document_id,
                "source_title": item.title,
                "source_published_at": item.source_published_at,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0002_contentitem_importance_score_source_crawl_depth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='date_confidence',
            field=models.CharField(choices=[('exact', '精确日期'), ('year_only', '仅年份'), ('unknown', '未知')], default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='extraction_quality_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='review_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='review_status',
            field=models.CharField(choices=[('candidate', '候选'), ('needs_review', '待审核'), ('published', '已发布'), ('blocked', '已屏蔽'), ('out_of_range', '超出时间范围')], default='published', max_length=30),
        ),
        migrations.AddField(
            model_name='source',
            name='allowed_domains',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='source',
            name='allowed_path_prefixes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='source',
            name='bootstrap_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='crawl_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='source',
            name='denied_path_patterns',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='source',
            name='last_error_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='last_success_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='max_depth',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='source',
            name='max_pages_per_run',
            field=models.PositiveIntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='source',
            name='schedule_group',
            field=models.CharField(blank=True, choices=[('web_twice_daily', '官网每日两次'), ('social_daily', '社媒每日一次'), ('manual', '仅手动')], max_length=40),
        ),
        migrations.CreateModel(
            name='ContentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=500)),
                ('source_title', models.CharField(blank=True, max_length=300)),
                ('source_published_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_sources', to='aggregator.contentitem')),
                ('raw_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aggregator.rawdocument')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered_content_sources', to='aggregator.source')),
            ],
            options={
                'verbose_name': '内容来源',
                'verbose_name_plural': '内容来源',
                'ordering': ['source__name', 'url'],
                'constraints': [models.UniqueConstraint(fields=('content_item', 'source', 'url'), name='unique_content_source_url')],
            },
        ),
        migrations.RunPython(backfill_review_state_and_sources, migrations.RunPython.noop),
    ]
