# Generated by Django 5.2.1 on 2026-05-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0004_normalize_public_gate_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usage_date', models.DateField()),
                ('provider', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=80)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('prompt_cache_hit_tokens', models.PositiveIntegerField(default=0)),
                ('prompt_cache_miss_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_prompt_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_completion_tokens', models.PositiveIntegerField(default=0)),
                ('cost_cny', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'AI每日用量',
                'verbose_name_plural': 'AI每日用量',
                'ordering': ['-usage_date', 'provider', 'model'],
                'constraints': [models.UniqueConstraint(fields=('usage_date', 'provider', 'model'), name='unique_ai_usage_daily')],
            },
        ),
    ]
