# Generated by Django 5.2.1 on 2026-07-12 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_runtime', '0004_agentapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='replay_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replays', to='agent_runtime.agentrun'),
        ),
    ]
